[build-system]
requires = ["flit_core >=3.2,<4", "myst_parser"]
build-backend = "flit_core.buildapi"

[project]
name = "JetDeploy"
authors = [{name = "JetDeploy", email = "info@jetdeploy.com"}]
dynamic = ["version", "description"]
